### ISSUE TITLE
t1_all_snp_alignment.fna: No such file or directory

### ISSUE THREAD

**Issue by mainguyenhuyen** [LANL-Bioinformatics/PhaME#21]
Hi, 

Thank you for your consideration. I ran into two problems when I installed and tested run PhaME. For some information, I am working on UPPMAX Rackham clusters. I have chosen to install PhaME like this: I installed dependencies by "module load" on Rackham server, then I clone the git by the time this issue was written. Then, I tested run by "test/TestAll.sh 1" in the correct PhaME directory. I ran into two problems as follows: 

1. Need nucmer --version >= 3.1 but you have 0 - please upgrade it.
My nucmer version is 4.0.0rc1, so there is an error in checking version here.

2. test/TestAll.sh: line 11: test/workdirs/t1_ebola_preads/results/alignments/t1_all_snp_alignment.fna: No such file or directory
So inside folder t1_ebola_preads, there are 4 fastq files. Maybe you have upgraded the testing data set or the testing test run program and forget to change the corresponding files along with them? 

Thank you.

**Comment by mshakya** [comment]
Hi, if this issue is still relevant, May i ask how are you installing the dependencies? You need to install them using conda (conda install phame) or separately. I recommend former option. Thanks.
